plugins {
    id 'fabric-loom'
    id 'com.github.johnrengelman.shadow'
}
base {
    archivesName = "${mod_name}-fabric-${minecraft_version}"
}
if (System.getenv('BUILD_NUMBER') != null) {
    version += "." + System.getenv('BUILD_NUMBER')
}

loom {
    if (project(":common").file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.accesswidener"))
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

configurations {
    shade
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation 'org.jetbrains:annotations:24.0.1'
    implementation project(path: ":common", configuration: "namedElements")

    modCompileOnly "maven.modrinth:sodium:mc1.20.1-0.5.3"
    modCompileOnly "maven.modrinth:iris:1.6.11+1.20.1"
    modCompileOnly "maven.modrinth:replaymod:1.20.1-2.6.15"
//    modRuntimeOnly "maven.modrinth:sodium:mc1.20.1-0.5.3"
//    modRuntimeOnly "maven.modrinth:iris:1.6.11+1.20.1"
//    modRuntimeOnly "maven.modrinth:replaymod:1.20.1-2.6.15"

    api(include("gg.moonflower:molang-compiler:${molang_compiler_version}"))

    api(include("org.lwjgl:lwjgl-opencl:$lwjgl_version")) {
        transitive false
    }
    api(include("org.lwjgl:lwjgl-shaderc:$lwjgl_version")) {
        transitive false
    }

    runtimeOnly(include("org.lwjgl:lwjgl-shaderc:$lwjgl_version:natives-linux"))
    runtimeOnly(include("org.lwjgl:lwjgl-shaderc:$lwjgl_version:natives-linux-arm64"))
    runtimeOnly(include("org.lwjgl:lwjgl-shaderc:$lwjgl_version:natives-macos"))
    runtimeOnly(include("org.lwjgl:lwjgl-shaderc:$lwjgl_version:natives-macos-arm64"))
    runtimeOnly(include("org.lwjgl:lwjgl-shaderc:$lwjgl_version:natives-windows"))
    runtimeOnly(include("org.lwjgl:lwjgl-shaderc:$lwjgl_version:natives-windows-arm64"))
}

tasks.withType(JavaCompile).configureEach {
    source(project(":common").sourceSets.main.allSource)
}
tasks.named("sourcesJar", Jar) {
    from(project(":common").sourceSets.main.allSource)
}

shadowJar {
    archiveClassifier = 'dev'
    configurations = [project.configurations.shade]
//    relocate "org.objectweb.asm", "${project.group}.lib.asm"
//    relocate "org.lwjgl.opencl", "${project.group}.lib.opencl"
//    relocate "gg.moonflower.molangcompiler", "${project.group}.lib.molangcompiler"
}

remapJar {
    dependsOn(shadowJar)
    inputFile = tasks.shadowJar.archiveFile
}

processResources {
    from project(":common").sourceSets.main.resources
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}